allow libxml2-progs uninstallation to succeed
currently libxml2-progs and sgml-common are put to transaction, but at
the time %preun of sgml-common runs, /usr/bin/xmlcatalog from
libxml2-progs is already removed, leaving sgml-common installed with
broken deps:

mark libxml2-progs-2.9.0-1.i686
Processing dependencies...
libxml2-progs-2.9.0-1.i686 marks sgml-common-0.6.3-7.noarch (req
/usr/bin/xmlcatalog)
There are 2 packages to remove (1 marked by dependencies):
R libxml2-progs-2.9.0-1.i686
D sgml-common-0.6.3-7.noarch
This operation will free 267.1KB of disk space.
Proceed? [N/y] y
Running rpm --erase --root / --noorder...
install-catalog: can not modify
"/etc/sgml/sgml-iso-entities-8879.1986.cat".
install-catalog: can not modify
"/etc/sgml/xml-iso-entities-8879.1986.cat".
/root/tmp/rpm-tmp.68860[6]: /usr/bin/xmlcatalog: not found
error: %preun(sgml-common-0.6.3-7.noarch) scriptlet failed, exit status
127

package libxml2-progs is not installed
..5.....  c /etc/sgml/sgml.conf
Unsatisfied dependencies for sgml-common-0.6.3-7.noarch:
        Requires: /usr/bin/xmlcatalog
        Requires: libxml2-progs